[package]
name = "bin"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
variables = { path = "../variables" }
